project:
  type: website
  output-dir: docs
  resources:
    - .nojekyll

website:
  title: "Meditations"
  description: "Meditations on data, economics, philosophy, and everything else"
  site-url: "https://coetsee.github.io"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "CV"
        href: cv.qmd
      - text: "About"
        href: about.qmd
  page-footer:
    center: "Hannes Coetsee"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
